### PR TITLE
fix: don't trigger onHashChange if path is not the same

### LINKED ISSUE #2791: can't navigate to other url
when in tutorial page(https://vuejs.org/tutorial/#step-1 page), I can't navigate to other page

### PR DESCRIPTION
**Pull request by brc-dd**
closes #2791

### CODE REVIEW

File: src/examples/utils.ts [hunk 1]
```diff
@@ -208,8 +208,15 @@ export function resolveNoBuildExample(
 }
 
 export function onHashChange(cb: () => void) {
-  window.addEventListener('hashchange', cb)
+  if (typeof document === 'undefined') return
+  const { pathname } = window.location
+  function handler() {
+    if (window.location.pathname === pathname) {
```
Comment (brc-dd) [inline src/examples/utils.ts:214]: Technically we could have also use .newURL / .oldURL on event argument, but looks like vitepress is dispatching only generic event object for hashchange. I'll fix it there and refactor this later.
